### ISSUE TITLE
QM9 raw dataset link broken?

### ISSUE THREAD

**Issue by MightyErnie** [rusty1s/pytorch_geometric#1794]
## 🐛 Bug

When trying to instantiate the QM9 dataset, I get a HTTP Error 403: Forbidden message

## To Reproduce

Launch python, run the following code and see the results below:

import torch_geometric
torch_geometric.datasets.QM9(root='./qm9')

Downloading https://s3-us-west-1.amazonaws.com/deepchem.io/datasets/molnet_publish/qm9.zip
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "3rdPartyLibs/torch_geometric/pytorch_geometric/torch_geometric/datasets/qm9.py", line 130, in __init__
    super(QM9, self).__init__(root, transform, pre_transform, pre_filter)
  File "3rdPartyLibs/torch_geometric/pytorch_geometric/torch_geometric/data/in_memory_dataset.py", line 54, in __init__
    pre_filter)
  File "3rdPartyLibs/torch_geometric/pytorch_geometric/torch_geometric/data/dataset.py", line 89, in __init__
    self._download()
  File "3rdPartyLibs/torch_geometric/pytorch_geometric/torch_geometric/data/dataset.py", line 141, in _download
    self.download()
  File "3rdPartyLibs/torch_geometric/pytorch_geometric/torch_geometric/datasets/qm9.py", line 165, in download
    file_path = download_url(self.raw_url, self.raw_dir)
  File "Projects/3rdPartyLibs/torch_geometric/pytorch_geometric/torch_geometric/data/download.py", line 34, in download_url
    data = urllib.request.urlopen(url, context=context)
  File "~/anaconda3/envs/ocp-models/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "~/anaconda3/envs/ocp-models/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "~/anaconda3/envs/ocp-models/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "~/anaconda3/envs/ocp-models/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "~/anaconda3/envs/ocp-models/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "~/anaconda3/envs/ocp-models/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

## Expected behavior

dataset downloads successfully

## Environment

* OS: Ubuntu 20.04
* Python version: 3.6.11
* PyTorch version: 1.7.0
* CUDA/cuDNN version: 11.0
* GCC version: 9.3.0-17ubuntu1~20.04
* Any other relevant information: Using the latest pytorch_geometric as of today: Nov 2, 2020

**Comment by MightyErnie** [comment]
This link works:

https://deepchemdata.s3-us-west-1.amazonaws.com/datasets/molnet_publish/qm9.zip

**Comment by rusty1s** [comment]
Thanks for letting me know. Fixed in master!

**Comment by LingxiaoShawn** [comment]
Same things happened for MoleculeNet.

**Comment by MightyErnie** [comment]
Might want to revisit all deepchem.io hosted links?

**Comment by rusty1s** [comment]
Indeed. This is now also fixed!

**Comment by czha5168** [comment]
Hi Matthias, Thanks for your quick actions!
I am reinstalled torch-geometric and try to download tox21 from MoleculeNet, but still receiving the same error message (urllib.error.HTTPError: HTTP Error 403: Forbidden). Could you please give me some comments or instructions? Much appreciate!

**Comment by rusty1s** [comment]
You can install from master via
```
pip install git+https://github.com/rusty1s/pytorch_geometric.git
```

**Comment by czha5168** [comment]
Thanks for your super-fast-awesome supports! It should be Glore1s, rather than Rusty1s.
