### ISSUE TITLE
Operation does not have an identity when edge_index = [2, 1] 

### ISSUE THREAD

**Issue by mahadafzal** [rusty1s/pytorch_geometric#2846]
I ran into this error before when working with my own dataset which I was able to solve through this previous issue [here](https://github.com/rusty1s/pytorch_geometric/issues/2064). It fixed the problem at the time, however, after successfully running experiments a 2 weeks ago I now run into a "Operation does not have an identity" error when the edge_index = [2,1].

I am using the link_pred.py example, and the error occurs when calling the train_test_split_edges method on a sample graph. 

Any suggestions for an additional work around?

**Comment by rusty1s** [comment]
Can you send me a snippet to reproduce? For example, the following works for me:
```python
import torch
from torch_geometric.data import Data
from torch_geometric.utils import train_test_split_edges

edge_index = torch.tensor([[0], [1]])
data = Data(edge_index=edge_index, num_nodes=2)
data = train_test_split_edges(data)
```
However, keep in mind that `train_test_split_edges` may not produce useful outputs regarding validation/test edges in case your `edge_index` only contains a single edge.

**Comment by mahadafzal** [comment]
I misread while debugging, apologies. The issue is when edge_index = [2, 0], so 

`import torch`
`from torch_geometric.data import Data`
`from torch_geometric.utils import train_test_split_edges`

`edge_index = torch.tensor([[],[]], dtype = torch.long)`
`data = Data(edge_index=edge_index, num_nodes=2)`
`data = train_test_split_edges(data)`

will reproduce the error.

Additionally, thank you for bringing up the useful outputs concern. I looked through the pyG methods but wanted further clarification. Could you elaborate on the outputs? I have two separate lists of graphs, containing exact train and test splits from a previous work. I call `train_test_split_edges` on them separately, with test ratio 0 and 1 respectively to train and test. The validation is always 0. Would that be enough to ensure that the training graphs list is meaningfully used to train the model and the test list is used to evaluate?

**Comment by rusty1s** [comment]
I fixed the issue with empty edge indices in PyG master, see [here](https://github.com/rusty1s/pytorch_geometric/commit/97d3177dc43858f66c07bb66d7dc12506b986199). I think if you have separate data objects for training and testing, there is no need to apply any splitting via `train_test_split_edges`, as the split is already given to you :)

**Comment by mahadafzal** [comment]
I am getting a new error on empty edge index.

`RuntimeError: max(): Expected reduction dim to be specified for input.numel() == 0. Specify the reduction dim with the 'dim' argument.`

It can be reproduced in the same manner and occurs on line 63 on storage.py, which is called in coalesce.py at line 22.

I still have a couple of questions regarding the custom train/test split using the link_pred.py example, but I'll create a separate issue for that.

**Comment by rusty1s** [comment]
This should have been already fixed in `torch-sparse`, see [here](https://github.com/rusty1s/pytorch_sparse/blob/master/torch_sparse/storage.py#L60-L63), but I agree that support for empty graphs still has some issues (although its use-cases are limited).
